# Builds and publishes the documentation website to gh-pages branch
name: Build docs

on:
  workflow_dispatch:

jobs:
  build_docs:
    runs-on: windows-latest
    steps:
      - name: Build Solution
        uses: ./.github/workflows/build.yml

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 7.x
        
      - name: Setup DocFX
        run: dotnet tool restore

      - name: Setup Bonsai
        working-directory: .bonsai
        run: ./Setup.ps1
        
      - name: Build Documentation
        working-directory: docs
        run: ./build.ps1

      - name: Publish to github pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site
          publish_branch: gh-pages
          force_orphan: true