# Builds and publishes the documentation website to gh-pages branch
name: Build docs

on:
  push:
    branches:
      - ng-docs-dev
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 7.x

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          ref: ng-docs-dev
      
      - name: Restore NuGet Packages
        run: msbuild -t:restore src\Bonsai.ML.sln

      - name: Setup DocFX
        run: dotnet tool restore

      - name: Build Documentation
        run: dotnet docfx docs/docfx.json

      - name: Move Build Output
        run: Move-Item docs\_site ..\docfx_site

      - name: Publish to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true