# Builds and runs unit tests for the examples
name: Test Examples

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10

      - name: Build Solution
        uses: ./.github/workflows/build.yml

      - name: Run Tests
        run: dotnet test Bonsai.ML.sln
